### ISSUE TITLE
dispose() method never called from bloc class. Potential memory leak.

### ISSUE THREAD

**Issue by SAGARSURI** [juliusspencer/Flutter-BLoC-Pattern#2]
I see you never called the dispose() method which you created in the bloc dart file. Its a memory leak. Can you tell me where you will be calling it in the screen class ?

**Comment by juliusspencer** [comment]
Hi, I think the best option would be to make the MyApp class a StatefulWidget and override the dispose method in the corresponding MyAppState class:

```dart
  @override
  void dispose() {
    _exampleBloc.dispose();
    super.dispose();
  }
```

**Comment by juliusspencer** [comment]
I'm also not sure whether there is a memory leak in this case when My App is destroyed.

**Comment by juliusspencer** [comment]
I've updated the code to demonstrate this, although I'm not sure whether it's necessary in this case due to the scope of the class containing the BLoC object.
